flags:
  servant-js:
    example: false
packages:
- servant/
- servant-blaze/
- servant-cassava/
- servant-client/
- servant-docs/
- servant-examples/
- servant-js/
- servant-lucid/
- servant-mock/
- servant-server/
extra-deps:
- engine-io-wai-1.0.2
- attoparsec-0.13.0.1
resolver: nightly-2015-07-24
